version: '3.7'

services:

  # daark:
  #   container_name: daark-dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  daark-prod:
    container_name: daark-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    restart: unless-stopped

